name: result_types
description: Rust inspired Result and Option types for Dart/Flutter.
version: 0.0.4
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
